# Generated by Django 6.1 on 2026-09-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rate', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='catalog.product', verbose_name='Товар')),
            ],
        ),
    ]
